version: '3.1'

services:
    fast-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'

    db:
        image: 'mariadb'
        restart: always
        environment:
            MYSQL_DATABASE: data
            MYSQL_ROOT_PASSWORD: password
        # volumes:
            # Pour lancer un dump automatiquement au montage du conteneur
            # - ./db/data.sql:/docker-entrypoint-initdb.d/dump.sql


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"
volumes:
    db: