version: '3.1'

services:
    fast-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'data'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - db:/var/lib/mysql


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"
volumes:
    db: