version: '3.1'

services:
    fast-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8004:8000'
        environment:
            - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/foo
        depends_on:
            - db
        links:
            - db

    db:
        image: postgres:13.4
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=data
        expose:
            - '5432'
        volumes:
            - db:/var/lib/postgres

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 5432
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - "8081:80"
volumes:
    db: