version: '3'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'group15'
      MYSQL_DATABASE: group15
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
