version: '3.1'

services:
    fast-api:
        build:
            context: .
            dockerfile: pythonDockerfile
        ports:
            - '8004:8000'
        environment:
            - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/data
        depends_on:
            - db
        links:
            - db

    db:
        image: postgres:13.3
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=data
        expose:
            - '5432'
        volumes:
            - db:/var/lib/postgres
        networks:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        links:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: postgres
        restart: always
        ports:
            - "8081:80"
        networks:
            - postgres

    server:
        container_name: server
        build:
            context: .
            dockerfile: serverDockerfile
        volumes:
            - ./nginx/:/etc/nginx/
        ports:
            - "80:80"
        command:  bash -c "service nginx start && sleep infinity"
            
        
volumes:
    db:

networks:
  postgres:
