version: '3.1'

services:
    fast-api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '2345:80'

    db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'group15'
            MYSQL_DATABASE: group15
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql


    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1